#! /bin/sh
 
#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh
feh --bg-fill /home/rodrigo/Escritorio/wallpaper
picom &
 
xrandr --output eDP1 --primary --mode 1366x768 --rotate normal --output HDMI2 --mode 1366x768 --rotate normal --above eDP1
 
 
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V
 
bspc config border_width         3
#bspc config normal_border_color \#005F73
#bspc config normal_border_color  \#00ffffff
bspc config focused_border_color \#ffffff
bspc config window_gap           8
 
 
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
 
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bash ~/.config/polybar/launch.sh --material
#bash ~/.config/polybar/material/scripts/random.sh you can uncomment this line if you want random colors for your polybar.
